<?php
use App\Models\Usuario;
use App\Controllers\PermissaoController;
use App\Middlewares\PermissionMiddleware;
?>

<section>
    <div class="card">

        <div class="title">
            <h1>Visualizar usuário</h1>
        </div>

        <form id="formVisualizarPessoa">

            <div class="input-field">
                <input type="text" name="nome" required disabled>
                <label for="nome">Nome</label>
            </div>

            <div class="input-field">
                <input type="text" name="usuario" required disabled>
                <label>Usuário</label>
            </div>

            <?php
            // Se for admin, mostrar o campo de cnpj, se for escritório, não mostrar.

            if (PermissionMiddleware::isAdmin()):
                ?>

                <div class="input-field">
                    <select name="cnpj_escritorio" id="cnpj_escritorio" disabled>
                        <option value=""></option>
                    </select>
                    <label>Escritório</label>
                </div>

                <?php
            endif;
            ?>

            <button class="btn btn-primary" id="btn_editar" type="button"> <i class="fa fa-pencil"></i> Editar</button>
            <a href="#" id="modalMudarSenha">Mudar senha</a>

            <span class="loading" id="loadingVisualizarUsuario"></span>

        </form>

    </div>

    <div class="card">

        <div class="bg-primary w3-text-white w3-padding w3-round-large w3-large w3-center w3-margin-bottom">
            Permissões
        </div>

        <div class="w3-container">

            <div class="w3-row" id="acoes">

                <!-- <div class="w3-col s12 m6 l4 w3-border w3-padding-small">
                    <h1 class="w3-large bg-primary w3-padding-small">CaixasController</h1>
                    <div class="customcheckbox">
                        <input type="checkbox" id="abrirCaixa" name="caixasController">
                        <label for="abrirCaixa"></label>
                        <p>abrirCaixa</p>
                        <span class="info">Permite abrir um caixa.</span>
                    </div>
                    <div class="customcheckbox">
                        <input type="checkbox" id="editarCaixa" name="caixasController">
                        <label for="editarCaixa"></label>
                        <p>editarCaixa</p>
                        <div class="info">Permite editar o nome do caixa.</div>
                    </div>

                </div> -->

            </div>

            <div class="loading" id="loadingAcoes"></div>
        </div>

        <div class="w3-container">
            <button class="btn btn-primary" id="salvar">
                <i class="fa fa-save"></i> Atualizar permissões
            </button>
        </div>

    </div>

</section>